baseURL = 'https://the-sumeet.github.io/'
languageCode = 'en-us'
title = "Sumeet's Blog"
theme = 'terminal'
paginate = 10
copyright = "Â© 2025 Sumeet"

# Enable emoji support in content
enableEmoji = true

# Generate robots.txt
enableRobotsTXT = true

# Enable sitemap
[sitemap]
  changefreq = "weekly"
  priority = 0.5

[params]
  # SEO
  description = "A blog about software engineering, APIs, front-end, mobile apps, and Linux"
  keywords = "software engineering, API, frontend, mobile apps, Linux, programming"
  author = "Sumeet"

  # Content type for posts pagination
  contentTypeName = "posts"

  # Theme colors: blue, green, red, pink, orange
  themeColor = "blue"

  # Read more button text
  ReadMore = "Read more"

[params.Logo]
  logoText = "Sumeet's Blog"

[[menu.main]]
  identifier = "blogs"
  name = "Blogs"
  url = "/posts"
  weight = 2